Gourav Verma<br>
DSC550 - Data Mining<br>
Summer-2020<br>
Week-8 : Assignment- 11.3.2 - SVD<br>
Book-Mining of Massive Datasets

In [1]:
# Import important libraries
import numpy as np
from scipy.linalg import svd

Use the SVD from Fig. 11.7. Suppose Leslie assigns rating 3 to Alien and rating 4 to Titanic, giving us a representation of leslie in “moviespace” of [0, 3, 0, 0, 4]. Find the representation of Leslie in concept space. What does that representation predict about how well Leslie would like the other movies appearing in our example data?

In [2]:
# Given data
Matrix = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],[0,0,0,2,2]])
print('Matrix -\n', Matrix)

U = np.array([[.14,0],[.42,0],[.56,0],[.70,0],[0,.60],[0,.75],[0,.30]])
print('U -\n', U)

summ = np.array([[12.4,0],[0,9.5]])
print('Sum -\n', summ)

V = np.array([[.58,.58,.58,0,0],[0,0,0,.71,.71]])
print('V -\n', V)

Matrix -
 [[1 1 1 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [5 5 5 0 0]
 [0 0 0 4 4]
 [0 0 0 5 5]
 [0 0 0 2 2]]
U -
 [[0.14 0.  ]
 [0.42 0.  ]
 [0.56 0.  ]
 [0.7  0.  ]
 [0.   0.6 ]
 [0.   0.75]
 [0.   0.3 ]]
Sum -
 [[12.4  0. ]
 [ 0.   9.5]]
V -
 [[0.58 0.58 0.58 0.   0.  ]
 [0.   0.   0.   0.71 0.71]]


In [3]:
# Representation for Leslie
leslie = np.array([0,3,0,0,4])

In [4]:
# Get concept space for Leslie 
cs = np.dot(leslie, V.T)
cs

array([1.74, 2.84])

In [5]:
# Get moview ratings for Leslie
np.dot(cs, V)

array([1.0092, 1.0092, 1.0092, 2.0164, 2.0164])

As per the movie data Leslie likes Titanic and Casablanca more than the other movies.