Gourav Verma<br>
DSC550 - Data Mining<br>
Summer-2020<br>
Week-8 : Exercise 8.1 - Dimensionality Reduction<br>
Books-Mining of Massive Datasets<br>

In [93]:
# Import importatant libraries
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
import scipy.linalg as la

### Part A

In [94]:
df_a = pd.DataFrame(np.array([[1, 2, 3, 4, 5], [2, 3, 2, 5, 3], [5, 5, 5, 3, 2]]), columns=['M', 'N', 'P', 'Q', 'R'], 
                  index=['A', 'B', 'C'])
df_a

M  N  P  Q  R
A  1  2  3  4  5
B  2  3  2  5  3
C  5  5  5  3  2

In [95]:
# Substract average of each rows
df_a = df_a.sub(df_a.mean(axis=1),axis=0)

# Substract average of each column
df_a = df_a.sub(df_a.mean(axis=0),axis=1)

# Display
df_a

M    N    P         Q    R
A -1.333333 -1.0  0.0  0.333333  2.0
B -0.333333  0.0 -1.0  1.333333  0.0
C  1.666667  1.0  1.0 -1.666667 -2.0

### Part B

Cosine similarity is equal the cosine of the angle between two non-zero vectors.<br>
We can compute pairwise cosine similarity on the rows of a sparse matrix directly using sklearn.

In [96]:
def cosine_sim(vect, alpha):
    """
    Function to calculate cosine similarity
    """
    for i in range(len(vect)):
        vect[i][5] = vect[i][5]*alpha   # Change ratings by multiplying with alpha
    
    V_sparse = sparse.csr_matrix(vect)
    similarities_sparse = cosine_similarity(V_sparse,dense_output=False)
    print('pairwise cosine similarity for alpha= {}:\n {}\n'.format(alpha, round(similarities_sparse, 3)))
    return
    

In [97]:
# Calculate pairwise cosine of angle for each alpha.
for a in [0, 0.5, 1, 2]:
    Vector = np.array([[1, 0, 1, 0, 1, 2], [1, 1, 0, 0, 1, 6], [0, 1, 0, 1, 0, 2]])
    cosine_sim(Vector, a)

pairwise cosine similarity for alpha= 0:
   (0, 0)	1.0
  (0, 1)	0.667
  (1, 0)	0.667
  (1, 1)	1.0
  (1, 2)	0.408
  (2, 1)	0.408
  (2, 2)	1.0

pairwise cosine similarity for alpha= 0.5:
   (0, 0)	1.0
  (0, 1)	0.722
  (0, 2)	0.289
  (1, 0)	0.722
  (1, 1)	1.0
  (1, 2)	0.667
  (2, 0)	0.289
  (2, 1)	0.667
  (2, 2)	1.0

pairwise cosine similarity for alpha= 1:
   (0, 0)	1.0
  (0, 1)	0.847
  (0, 2)	0.617
  (1, 0)	0.847
  (1, 1)	1.0
  (1, 2)	0.85
  (2, 0)	0.617
  (2, 1)	0.85
  (2, 2)	1.0

pairwise cosine similarity for alpha= 2:
   (0, 0)	1.0
  (0, 1)	0.946
  (0, 2)	0.865
  (1, 0)	0.946
  (1, 1)	1.0
  (1, 2)	0.953
  (2, 0)	0.865
  (2, 1)	0.953
  (2, 2)	1.0



### Part C

In [98]:
v = np.array([2/7, 3/7, 6/7]) # Given matrix

r = np.random.randn(3)        # Generate random matrix
r -= r.dot(v) * v / np.linalg.norm(v)**2   # Get orthonormal matrix
k = np.cross(v, r)            # Get cross product
print(k)                      # Print the matrix

# Validate
np.dot(k, v)

[-1.26019067  0.46501084  0.18755814]


0.0

### Part D

In [99]:
p = np.array([[1,1],[2,2],[3,4]])  # Given 2d array
q = np.dot(p.transpose(),p)        # Get dot product with transporse matrix
eigvals, eigvecs = la.eig(q)       # Compute eigenvalue and eigenvectors
eigvecs                            # Display eigenvectors

array([[-0.77512996, -0.63180182],
       [ 0.63180182, -0.77512996]])

### Part E

In [100]:
e = np.array([1, 2, 3])   # Given Matrix
og = np.array([2, 2, -2]) # Orthogonal matrix

# Validate
np.dot(e, og)

0

### Part F

In [101]:
X = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 0]])  # Given matrix
np.linalg.pinv(X)   # Compute the (Moore-Penrose) pseudo-inverse of the matrix.

array([[1. , 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0. ]])