In [1]:
# Import important libraries

import numpy as np

#### Exercise: 12.2.1 (c)

In [2]:
dict1 = {'a':(1, 1, 0, 1, 1, -1, +1), 'b':(0, 0, 1, 1, 1, -1, -1), 'c':(0, 1, 1, 0, 0, -1, +1), 'd':(1, 0, 0, 1, 0, -1, -1), 
        'e':(1, 0, 1, 0, 1, -1, +1), 'f':(1, 0, 1, 1, 0, -1, -1)}
dict1

{'a': (1, 1, 0, 1, 1, -1, 1),
 'b': (0, 0, 1, 1, 1, -1, -1),
 'c': (0, 1, 1, 0, 0, -1, 1),
 'd': (1, 0, 0, 1, 0, -1, -1),
 'e': (1, 0, 1, 0, 1, -1, 1),
 'f': (1, 0, 1, 1, 0, -1, -1)}

In [3]:
# Convert to Matrix
names = ['a', 'b', 'c', 'd', 'e', 'f']

dataMatrix = np.array([dict1[i] for i in names])
dataMatrix

array([[ 1,  1,  0,  1,  1, -1,  1],
       [ 0,  0,  1,  1,  1, -1, -1],
       [ 0,  1,  1,  0,  0, -1,  1],
       [ 1,  0,  0,  1,  0, -1, -1],
       [ 1,  0,  1,  0,  1, -1,  1],
       [ 1,  0,  1,  1,  0, -1, -1]])

In [4]:
# Basic Method with variable threshold

l_rate = 0.5
w_matrix = [0, 0, 0, 0, 0, 0]
for i in range(len(dataMatrix)):
    print('----------')
    print('old', w_matrix)
    w = np.sum(w_matrix*dataMatrix[i][:-1])
    print('i = ', i, 'w = ', w)
    if w == 0:
        w_matrix = w_matrix + l_rate*dataMatrix[i][-1]*dataMatrix[i][:-1]
    elif w > 0 and dataMatrix[i][-1] == -1:
        print('Incorrect') 
        w_matrix = w_matrix + l_rate*dataMatrix[i][-1]*dataMatrix[i][:-1]
    elif w < 0 and dataMatrix[i][-1] == +1:
        print('Correct')
    print('new', w_matrix)

----------
old [0, 0, 0, 0, 0, 0]
i =  0 w =  0
new [ 0.5  0.5  0.   0.5  0.5 -0.5]
----------
old [ 0.5  0.5  0.   0.5  0.5 -0.5]
i =  1 w =  1.5
Incorrect
new [ 0.5  0.5 -0.5  0.   0.   0. ]
----------
old [ 0.5  0.5 -0.5  0.   0.   0. ]
i =  2 w =  0.0
new [ 0.5  1.   0.   0.   0.  -0.5]
----------
old [ 0.5  1.   0.   0.   0.  -0.5]
i =  3 w =  1.0
Incorrect
new [ 0.   1.   0.  -0.5  0.   0. ]
----------
old [ 0.   1.   0.  -0.5  0.   0. ]
i =  4 w =  0.0
new [ 0.5  1.   0.5 -0.5  0.5 -0.5]
----------
old [ 0.5  1.   0.5 -0.5  0.5 -0.5]
i =  5 w =  1.0
Incorrect
new [ 0.   1.   0.  -1.   0.5  0. ]


#### Exercise 12.2.1 (d)
##### Not finished

In [5]:
# Winnow Method

dataMatrix

array([[ 1,  1,  0,  1,  1, -1,  1],
       [ 0,  0,  1,  1,  1, -1, -1],
       [ 0,  1,  1,  0,  0, -1,  1],
       [ 1,  0,  0,  1,  0, -1, -1],
       [ 1,  0,  1,  0,  1, -1,  1],
       [ 1,  0,  1,  1,  0, -1, -1]])

In [6]:
def cal_w(w, X, act):
    j = 0
    if act == 'promote':
        for b in X:
            if b == 1:
                w[j] = w[j]*2
            j += 1
        # return [w[j]*2 for b in X if b == 1]
    elif act == 'demote':
        for b in X:
            if b == 1:
                w[j] = w[j]/2
            j += 1
        #return [w[j]/2 for b in X if b == 1]
        
    return w

In [7]:
# initialize w
w = [1, 1, 1, 1, 1, 1]
b = 0
z = 0
while b < 7:
    print('b=', b)
    for i in range(len(dataMatrix)):
        print('----------')
        wold = w
        print('old', wold)
        wi = sum(w*dataMatrix[i][:-1])
        print(wi)
        if wi > 0 and dataMatrix[i][-1] == -1:
            print(dataMatrix[i][:-2])
            w = cal_w(w, dataMatrix[i][:-2], act='demote' )
            w[-1] = w[-1]*2
        elif (wi < 0 and dataMatrix[i][-1] == 1) or wi == 0:
            w = cal_w(w, dataMatrix[i][:-2], act='promote' )
            w[-1] = w[-1]/2
        #elif abs(wi) < 0.001:
        #    z = 1
        
        print(i, w)
        print(type(w))
    
    #if z == 1:
    #    break
    b += 1

b= 0
----------
old [1, 1, 1, 1, 1, 1]
3
0 [1, 1, 1, 1, 1, 1]
<class 'list'>
----------
old [1, 1, 1, 1, 1, 1]
2
[0 0 1 1 1]
1 [1, 1, 0.5, 0.5, 0.5, 2]
<class 'list'>
----------
old [1, 1, 0.5, 0.5, 0.5, 2]
-0.5
2 [1, 2, 1.0, 0.5, 0.5, 1.0]
<class 'list'>
----------
old [1, 2, 1.0, 0.5, 0.5, 1.0]
0.5
[1 0 0 1 0]
3 [0.5, 2, 1.0, 0.25, 0.5, 2.0]
<class 'list'>
----------
old [0.5, 2, 1.0, 0.25, 0.5, 2.0]
0.0
4 [1.0, 2, 2.0, 0.25, 1.0, 1.0]
<class 'list'>
----------
old [1.0, 2, 2.0, 0.25, 1.0, 1.0]
2.25
[1 0 1 1 0]
5 [0.5, 2, 1.0, 0.125, 1.0, 2.0]
<class 'list'>
b= 1
----------
old [0.5, 2, 1.0, 0.125, 1.0, 2.0]
1.625
0 [0.5, 2, 1.0, 0.125, 1.0, 2.0]
<class 'list'>
----------
old [0.5, 2, 1.0, 0.125, 1.0, 2.0]
0.125
[0 0 1 1 1]
1 [0.5, 2, 0.5, 0.0625, 0.5, 4.0]
<class 'list'>
----------
old [0.5, 2, 0.5, 0.0625, 0.5, 4.0]
-1.5
2 [0.5, 4, 1.0, 0.0625, 0.5, 2.0]
<class 'list'>
----------
old [0.5, 4, 1.0, 0.0625, 0.5, 2.0]
-1.4375
3 [0.5, 4, 1.0, 0.0625, 0.5, 2.0]
<class 'list'>
----------

#### Exercise 12.3.2 (a)

Support vectors are those points which lies closest to decision surface or we can say the hyperplane which separates the two classes

In 3 dimensional space, the equation of hyperplane which separates positive and negative example will be x + y + z = 10

Here its just sufficient to find nearest point based on value of |x+y+z-10|

In [8]:
dict1 = {'a':((3, 4, 5), +1), 'b':((2, 7, 2), +1), 'c':((5, 5, 5), +1), 'd':((1, 2, 3), -1), 'e':((3, 3, 2), -1), 
         'f':((2, 4, 1), -1)}

# Convert to matrix
names = ['a', 'b', 'c', 'd', 'e', 'f']
dataMatrix = np.array([dict1[i] for i in names])
dataMatrix

array([[(3, 4, 5), 1],
       [(2, 7, 2), 1],
       [(5, 5, 5), 1],
       [(1, 2, 3), -1],
       [(3, 3, 2), -1],
       [(2, 4, 1), -1]], dtype=object)

In [9]:
pmin = 10
nmin = 10
p = 0
n = 0
for i in range(len(dataMatrix)):
    dist = abs(sum(dataMatrix[i][0])-10)
    if dataMatrix[i][1] == 1:
        if dist < pmin:
            pmin = dist
            p = i
    if dataMatrix[i][1] == -1:
        if dist < nmin:
            nmin = dist
            n = i

print('In positive side ', dataMatrix[p][0], 'is the support vector. Distance from hyperplane = ', pmin)
print('In negative side ', dataMatrix[n][0], 'is the support vector. Distance from hyperplane = ', nmin)

In positive side  (2, 7, 2) is the support vector. Distance from hyperplane =  1
In negative side  (3, 3, 2) is the support vector. Distance from hyperplane =  2
